$(document).ready(function(){
    $("#menu").load("html/menuAdmin.html"); 
    $("#cabecera").load("html/cabeceraWeb.html");  
    $("#ventanaModal").load("html/modalInicioSesion.html");  
    $("#ventanaModalUsuario").load("html/modalUsuario.html");  
    $("#ventanaModalAdmin").load("html/modalAdmin.html");   
    $("#contenedorSlider").load("html/slider.html");  
    $("#pie").load("html/pie.html"); 
})
